{"url": "https://en.wikipedia.org/wiki/Robotics"}
{"url": "https://en.wikipedia.org/wiki/Robot"}
{"url": "https://en.wikipedia.org/wiki/Reinforcement_learning"}
{"url": "https://en.wikipedia.org/wiki/Robot_Operating_System"}
{"url": "https://en.wikipedia.org/wiki/Intelligent_agent"}
{"url": "https://en.wikipedia.org/wiki/Software_agent"}
{"url": "https://en.wikipedia.org/wiki/Robotic_process_automation"}
{"url": "https://en.wikipedia.org/wiki/Chatbot"}
{"url": "https://en.wikipedia.org/wiki/Applications_of_artificial_intelligence"}
{"url": "https://en.wikipedia.org/wiki/Android_(robot)"}
